# api for listing all leads

#method url
# content-type
# authorization

# data

###
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###

GET http://127.0.0.1:8000/api/leads/
Authorization: Token 4863ccd64e0e4fe7664a1a899bda2c6ae0aeceef

# api for adding a new lead
###

POST http://127.0.0.1:8000/api/leads/
Content-Type: application/json
Authorization: Token 4863ccd64e0e4fe7664a1a899bda2c6ae0aeceef

{
  "name": "shan",
  "mobile": "7865456543",
  "email": "shan@gmail.com",
  "college": "abc",
  "qualification": "mca",
  "passout_year": "2024",
  "source": "referral",
  "course": "MEARN",
  "course_mode": "OFFLINE",
  "status": "PROCEEDTOADMISSION"
}


# api call fetching a specific lead
###

GET http://127.0.0.1:8000/api/leads/4/
Authorization: Token 4863ccd64e0e4fe7664a1a899bda2c6ae0aeceef


# api call for updating lead
###
PUT http://127.0.0.1:8000/api/leads/4/
Content-Type: application/json
Authorization: Token 4863ccd64e0e4fe7664a1a899bda2c6ae0aeceef

{
  "name": "shan",
  "mobile": "7865456543",
  "email": "shan@gmail.com",
  "college": "abc",
  "qualification": "mca",
  "passout_year": "2023",
  "source": "referral",
  "course": "MEARN",
  "course_mode": "OFFLINE",
  "status": "PROCEEDTOADMISSION"
}


# api call for deleting lead

###

DELETE http://127.0.0.1:8000/api/leads/3/
Authorization: Token 4863ccd64e0e4fe7664a1a899bda2c6ae0aeceef